// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5wqAo9QjbptymE7rq3u1rdIWF_P7q58',
    appId: '1:627810999606:web:658523fa7c0a34a0cb2797',
    messagingSenderId: '627810999606',
    projectId: 'test-5dc1c',
    authDomain: 'test-5dc1c.firebaseapp.com',
    storageBucket: 'test-5dc1c.appspot.com',
    measurementId: 'G-J8V8FDXJKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyWWcsvlmnA-sJxBeB3IbMBEWtNsURs4',
    appId: '1:627810999606:android:4b34c0209a11a88bcb2797',
    messagingSenderId: '627810999606',
    projectId: 'test-5dc1c',
    storageBucket: 'test-5dc1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscbYVzaukExn2XiVBE3Dg8uEYBb2BG4U',
    appId: '1:627810999606:ios:15671de3e6cce539cb2797',
    messagingSenderId: '627810999606',
    projectId: 'test-5dc1c',
    storageBucket: 'test-5dc1c.appspot.com',
    iosClientId: '627810999606-ubdqe6kg7iog3samdrkdbfngvimbupqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAscbYVzaukExn2XiVBE3Dg8uEYBb2BG4U',
    appId: '1:627810999606:ios:15671de3e6cce539cb2797',
    messagingSenderId: '627810999606',
    projectId: 'test-5dc1c',
    storageBucket: 'test-5dc1c.appspot.com',
    iosClientId: '627810999606-ubdqe6kg7iog3samdrkdbfngvimbupqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
